version: '3.8'
services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:   ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: ${SPRING_R2DBC_URL}
      SPRING_R2DBC_USERNAME: ${SPRING_R2DBC_USERNAME}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}

      SPRING_LIQUIBASE_URL: ${SPRING_LIQUIBASE_URL}
      SPRING_LIQUIBASE_USER: ${SPRING_LIQUIBASE_USER}
      SPRING_LIQUIBASE_PASSWORD: ${SPRING_LIQUIBASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
