endpoint:
  global: /api/v1/
  deposit-withdraw: wallet
  get-balance: wallets/{wallets_uuid}

spring:
  main:
    web-application-type: reactive
  application:
    name: JavaCodeApplication

  data:
    r2dbc:
      repositories:
        enabled: true

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123456
    user: root
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public

  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: root
    password: 123456

server:
  port: 8080